/*
 * Generated by XDoclet - Do not edit!
 */
package com.prokits.custom.sb;

/**
 * Home interface for PURMI07_Mail.
 * @generated 
 * @wtp generated
 */
public interface PURMI07_MailHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/PURMI07_Mail";
   public static final String JNDI_NAME="PURMI07_Mail";

   public com.prokits.custom.sb.PURMI07_Mail create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
