/*
 * Generated by XDoclet - Do not edit!
 */
package com.prokits.custom.sb;

/**
 * Local home interface for PURMI07_Mail.
 * @generated 
 * @wtp generated
 */
public interface PURMI07_MailLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/PURMI07_MailLocal";
   public static final String JNDI_NAME="PURMI07_MailLocal";

   public com.prokits.custom.sb.PURMI07_MailLocal create()
      throws javax.ejb.CreateException;

}
