/*
 * Generated by XDoclet - Do not edit!
 */
package com.prokits.custom.sb;

/**
 * Remote interface for PURMI07_Mail.
 * @generated 
 * @wtp generated
 */
public interface PURMI07_Mail
   extends javax.ejb.EJBObject
{
   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public java.lang.String foo( java.lang.String param )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public void sendPDF( com.dsc.nana.domain.form.FormInstance tFormInstance )
      throws java.rmi.RemoteException;

}
