/*
 * Generated by XDoclet - Do not edit!
 */
package com.prokits.custom.sb;

/**
 * Remote interface for FO_121D.
 * @generated 
 * @wtp generated
 */
public interface FO_121D
   extends javax.ejb.EJBObject
{
   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public java.lang.String foo1( java.lang.String param )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public void apiUpdateFiles( com.dsc.nana.domain.form.FormInstance pForm )
      throws java.rmi.RemoteException;

}
