/*
 * Generated by XDoclet - Do not edit!
 */
package com.prokits.custom.sb;

/**
 * Local home interface for FO_121D.
 * @generated 
 * @wtp generated
 */
public interface FO_121DLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/FO_121DLocal";
   public static final String JNDI_NAME="FO_121DLocal";

   public com.prokits.custom.sb.FO_121DLocal create()
      throws javax.ejb.CreateException;

}
