/*
 * Generated by XDoclet - Do not edit!
 */
package com.prokits.custom.sb;

/**
 * Home interface for FO_121D.
 * @generated 
 * @wtp generated
 */
public interface FO_121DHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/FO_121D";
   public static final String JNDI_NAME="FO_121D";

   public com.prokits.custom.sb.FO_121D create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
