/*
 * Generated by XDoclet - Do not edit!
 */
package com.prokits.custom.sb;

/**
 * Local interface for FO_121D.
 * @generated 
 * @wtp generated
 */
public interface FO_121DLocal
   extends javax.ejb.EJBLocalObject
{

   public byte[] getBytesFromFile( java.lang.String pOID ) throws java.io.IOException;

}
