/*
 * Generated by XDoclet - Do not edit!
 */
package com.prokits.custom.sb;

/**
 * Local interface for PURMI07_Form.
 * @generated 
 * @wtp generated
 */
public interface PURMI07_FormLocal
   extends javax.ejb.EJBLocalObject
{

}
