/*
 * Generated by XDoclet - Do not edit!
 */
package com.prokits.custom.sb;

/**
 * Home interface for PURMI07_SH_PDF.
 * @generated 
 * @wtp generated
 */
public interface PURMI07_SH_PDFHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/PURMI07_SH_PDF";
   public static final String JNDI_NAME="PURMI07_SH_PDF";

   public com.prokits.custom.sb.PURMI07_SH_PDF create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
