/*
 * Generated by XDoclet - Do not edit!
 */
package com.prokits.custom.sb;

/**
 * Local home interface for PURMI07_SH_PDF.
 * @generated 
 * @wtp generated
 */
public interface PURMI07_SH_PDFLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/PURMI07_SH_PDFLocal";
   public static final String JNDI_NAME="PURMI07_SH_PDFLocal";

   public com.prokits.custom.sb.PURMI07_SH_PDFLocal create()
      throws javax.ejb.CreateException;

}
