/*
 * Generated by XDoclet - Do not edit!
 */
package com.prokits.custom.sb;

/**
 * Local home interface for PURMI07_Oin1_Form.
 * @generated 
 * @wtp generated
 */
public interface PURMI07_Oin1_FormLocalHome
   extends javax.ejb.EJBLocalHome
{
   public static final String COMP_NAME="java:comp/env/ejb/PURMI07_Oin1_FormLocal";
   public static final String JNDI_NAME="PURMI07_Oin1_FormLocal";

   public com.prokits.custom.sb.PURMI07_Oin1_FormLocal create()
      throws javax.ejb.CreateException;

}
