/*
 * Generated by XDoclet - Do not edit!
 */
package com.prokits.custom.sb;

/**
 * Home interface for PURMI07_SH_Form.
 * @generated 
 * @wtp generated
 */
public interface PURMI07_SH_FormHome
   extends javax.ejb.EJBHome
{
   public static final String COMP_NAME="java:comp/env/ejb/PURMI07_SH_Form";
   public static final String JNDI_NAME="PURMI07_SH_Form";

   public com.prokits.custom.sb.PURMI07_SH_Form create()
      throws javax.ejb.CreateException,java.rmi.RemoteException;

}
