/*
 * Generated by XDoclet - Do not edit!
 */
package com.prokits.custom.sb;

/**
 * Remote interface for PURMI07_SH_Form.
 * @generated 
 * @wtp generated
 */
public interface PURMI07_SH_Form
   extends javax.ejb.EJBObject
{
   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public java.lang.String foo( java.lang.String param )
      throws java.rmi.RemoteException;

   /**
    * <!-- begin-xdoclet-definition -->
    * @generated //TODO: Must provide implementation for bean method stub    */
   public com.dsc.nana.domain.form.FormInstance getFormData( com.dsc.nana.domain.form.FormInstance pForm )
      throws java.rmi.RemoteException;

}
